version: 2
models:
  - name: stg_hosts
    columns:
      - name: host_id
        tests:
          - unique
          - not_null
      

  - name: stg_listings
    columns:
      - name: listing_id
        tests:
          - not_null
          - unique:
              config:
                severity: error
                error_if: "> 10"
                warn_if: ">5"
      - name: listing_name
        tests:
          - not_null
      - name: listing_url
        tests:
          - not_null

      - name: room_type
        tests:
          - accepted_values:
              values:
                - 'Private room'
                - 'Entire home/apt'
                - 'Shared room'
                - 'Hotel room'
                - 'Entire home'
                - 'Entire Villa'
              config:
                where: "created_at = updated_at"
                limit: 1000 

      - name: host_id
        tests:
          - relationships:
              field: 'host_id'
              to: ref('stg_hosts')
      - name: price_str
        tests:
          - negative_values