version: 2
models:
  - name: stg_hosts
    description: this table holds the host's details
    columns:
      - name: host_id
        description: unique identifier for each hosts
        tests:
          - unique
          - not_null
      

  - name: stg_listings
    columns:
      - name: listing_id
        tests:
          - not_null
          - unique:
              config:
                severity: error
                error_if: "> 10"
                warn_if: ">5"
      - name: listing_name
        tests:
          - not_null
      - name: listing_url
        tests:
          - not_null
      - name: price_str
        tests:
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 0
              max_value: 5000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^\\$[0-9][0-9\\.]+$"

      - name: minimum_nights
        description: '{{ doc ("dim_listings_minimum_nights") }}'
        tests:
          - negative_values:
              config:
                store_failures: true
                

      - name: room_type
        description: the type of rooms available
        tests:
          - accepted_values:
              values:
                - 'Private room'
                - 'Entire home/apt'
                - 'Shared room'
                - 'Hotel room'
                - 'Entire home'
                - 'Entire Villa'
              config:
                where: "created_at = updated_at"
                limit: 1000 

      - name: host_id
        description: host's id referencing the host table
        tests:
          - relationships:
              field: 'host_id'
              to: ref('stg_hosts')
              
      - name: price_str
        tests:
          - negative_values:
              config:
                store_failures: true

  

